import os

from fastapi.staticfiles import StaticFiles


def register_routes(
    app,
    *,
    create_auth_router,
    create_admin_activity_router,
    create_admin_devices_router,
    create_admin_diagnostics_router,
    create_admin_initials_router,
    create_admin_maintenance_router,
    create_admin_backfill_router,
    create_admin_exports_router,
    create_erasure_insights_router,
    create_qa_insights_router,
    create_metrics_analytics_router,
    create_overall_stats_router,
    create_webhooks_router,
    create_device_lookup_router,
    create_bottleneck_router,
    create_static_pages_router,
    create_hwid_router,
    admin_password,
    manager_password,
    device_token_expiry_days,
    get_client_ip,
    get_client_ips,
    is_local_network,
    local_networks,
    is_device_token_valid,
    load_device_tokens,
    save_device_tokens,
    get_last_server_error,
    touch_device_token,
    generate_device_token,
    require_admin,
    require_manager_or_admin,
    activity_log,
    db_module,
    qa_export_module,
    excel_export_module,
    psutil_module,
    trace_snapshot_threshold_mb,
    take_tracemalloc_snapshot,
    set_last_server_error,
    cache_get,
    cache_set,
    webhook_api_keys,
    hwid_log_path,
    get_role_from_request,
    ttl_cache_cls,
    compute_qa_dashboard_data,
    backfill_progress,
    frontend_pages_dir,
    frontend_js_dir,
    frontend_css_dir,
):
    app.include_router(
        create_auth_router(
            admin_password=admin_password,
            manager_password=manager_password,
            device_token_expiry_days=device_token_expiry_days,
            get_client_ip=get_client_ip,
            get_client_ips=get_client_ips,
            is_local_network=is_local_network,
            is_device_token_valid=is_device_token_valid,
            load_device_tokens=load_device_tokens,
            save_device_tokens=save_device_tokens,
            touch_device_token=touch_device_token,
            generate_device_token=generate_device_token,
        )
    )
    app.include_router(
        create_admin_activity_router(
            require_admin=require_admin,
            load_device_tokens=load_device_tokens,
            activity_log=activity_log,
            get_activity_writer=lambda: getattr(app.state, "activity_writer", None),
            db_module=db_module,
        )
    )
    app.include_router(
        create_admin_devices_router(
            require_admin=require_admin,
            require_manager_or_admin=require_manager_or_admin,
            load_device_tokens=load_device_tokens,
            save_device_tokens=save_device_tokens,
            get_last_server_error=get_last_server_error,
        )
    )
    app.include_router(
        create_admin_diagnostics_router(
            require_admin=require_admin,
            db_module=db_module,
            get_mariadb_connection=qa_export_module.get_mariadb_connection,
            get_client_ip=get_client_ip,
            get_client_ips=get_client_ips,
            is_local_network=is_local_network,
            is_device_token_valid=is_device_token_valid,
            trusted_viewer_networks=local_networks,
            activity_log=activity_log,
        )
    )
    app.include_router(
        create_admin_initials_router(
            require_admin=require_admin,
            db_module=db_module,
        )
    )
    app.include_router(
        create_admin_maintenance_router(
            require_admin=require_admin,
            db_module=db_module,
            take_tracemalloc_snapshot=take_tracemalloc_snapshot,
        )
    )
    app.include_router(
        create_admin_backfill_router(
            require_admin=require_admin,
            require_manager_or_admin=require_manager_or_admin,
            db_module=db_module,
            progress_state=backfill_progress,
        )
    )
    app.include_router(
        create_admin_exports_router(
            require_manager_or_admin=require_manager_or_admin,
            db_module=db_module,
            excel_export_module=excel_export_module,
            psutil_module=psutil_module,
            trace_snapshot_threshold_mb=trace_snapshot_threshold_mb,
            take_tracemalloc_snapshot=take_tracemalloc_snapshot,
            set_last_server_error=set_last_server_error,
        )
    )
    app.include_router(
        create_erasure_insights_router(
            db_module=db_module,
        )
    )
    app.include_router(
        create_qa_insights_router(
            cache_get=cache_get,
            cache_set=cache_set,
        )
    )
    app.include_router(
        create_metrics_analytics_router(
            db_module=db_module,
            cache_get=cache_get,
            cache_set=cache_set,
        )
    )
    app.include_router(
        create_overall_stats_router(
            qa_export_module=qa_export_module,
            db_module=db_module,
            require_manager_or_admin=require_manager_or_admin,
        )
    )
    app.include_router(
        create_webhooks_router(
            db_module=db_module,
            webhook_api_keys=webhook_api_keys,
        )
    )
    app.include_router(
        create_device_lookup_router(
            db_module=db_module,
            qa_export_module=qa_export_module,
            require_manager_or_admin=require_manager_or_admin,
            get_role_from_request=get_role_from_request,
            ttl_cache_cls=ttl_cache_cls,
        )
    )
    app.include_router(
        create_bottleneck_router(
            db_module=db_module,
            qa_export_module=qa_export_module,
            require_manager_or_admin=require_manager_or_admin,
            compute_qa_dashboard_data=compute_qa_dashboard_data,
            cache_get=cache_get,
            cache_set=cache_set,
            ttl_cache_cls=ttl_cache_cls,
            backfill_progress=backfill_progress,
        )
    )

    app.include_router(
        create_static_pages_router(
            frontend_pages_dir=frontend_pages_dir,
            frontend_js_dir=frontend_js_dir,
            frontend_css_dir=frontend_css_dir,
            config_json_path=os.path.join("config", "config.json"),
        )
    )

    app.include_router(
        create_hwid_router(
            webhook_api_keys=webhook_api_keys,
            hwid_log_path=hwid_log_path,
        )
    )

    app.mount("/", StaticFiles(directory=".", html=True), name="static")
